services:
  - type: web
    name: backend
    runtime: node
    plan: free

    buildCommand: |
      npm ci --workspace packages/backend --omit=dev
      cd packages/backend && npm run build
    startCommand: node packages/backend/dist/server.js
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /health
